### PR TITLE
Anttu t patch 5

### PR DESCRIPTION
**Pull request by anttu-t**

### CODE REVIEW

**Review by tombeynon — CHANGES_REQUESTED** [review]
Looks like this PR adds two new folders for the same validator - can you sort that out?

**Comment by anttu-t** [comment]
My first time with Github, sorry...

Beagle2 should be the valid one, but I could not find a way to delete beagle. :,(


Anttu


⁣Hanki BlueMail for Android ​


26. marrask. 2022 klo 19.47, 19.47, Tom Beynon ***@***.***> kirjoitti:

**Review by tombeynon — APPROVED** [review]

**Comment by tombeynon** [comment]
All sorted :)

**Comment by anttu-t** [comment]
Thanks!!!

Anttu


⁣Hanki BlueMail for Android ​


26. marrask. 2022 klo 20.00, 20.00, Tom Beynon ***@***.***> kirjoitti:

**Pull request merged**
