### PR TITLE
Moniker Update

### PR DESCRIPTION
**Pull request by vNodesV**
Trying to fix the issue where autostake is not grabbing the correct account to check delegations/grants.

### CODE REVIEW

**Comment by tombeynon** [comment]
Hey @vNodesV! Name won't be affecting this. It's just your validator address that we use to source delegations, then we check each of the delegators for grants to your restake address.

If you're not seeing the correct delegations count (before the individual grant checks), then it'll be your validator operator address which is incorrect.

If you're seeing the correct delegations count, but no grants, then your restake bot address might be wrong.

**Comment by vNodesV** [comment]
HI brother! that's the thing. Both bot and validator addresses are correct. The service is correct. everything is dandy lol but the issue is... when docker-compose for sifchain, something it grabs the correct validator, i'd say 25% of the time. the rest, it's the old "wrong" one. It's like there's a cached address somewhere. I was wondering, should I try to update and remove the --no-cache flag?

**Comment by tombeynon** [comment]
Very strange. There's no caching happening here, other than the validator registry being updated every 15 mins. Sounds like something else is up, but let me know what you find! Want me to merge this either way?

**Comment by vNodesV** [comment]
please.

**Comment by vNodesV** [comment]
yeah so, same thing. that's so weird.  let me kill the vm and start fresh.  i'll update you later.

**Pull request merged**
