### PR TITLE
Added Nom, Comdex and updated run times

### PR DESCRIPTION
**Pull request by onivalidator**

### CODE REVIEW

**Comment by tombeynon** [comment]
JSON is invalid, I'll sort shortly

**Comment by windpowerstake** [comment]
I'm going to cut this PR into pieces and submit it with oni's request, so they can start operating, I hope it does not conflict with any work you are doing now

**Comment by windpowerstake** [comment]
got them comdex & stride on commit: ee30b166e82380163f214b4795f83911cd6156d2  
changed to teritori to 5 minutes on commit: ee30b166e82380163f214b4795f83911cd6156d2

**Comment by gh0stdotexe** [comment]
> got them comdex & stride on commit: [fbc1c85](https://github.com/eco-stake/validator-registry/commit/fbc1c85c99aaee4e02ccb9918998e9f9aa1f6a2d) changed to teritori to 5 minutes on commit: [ee30b16](https://github.com/eco-stake/validator-registry/commit/ee30b166e82380163f214b4795f83911cd6156d2) put them alphabetically on commit: [1d05f36](https://github.com/eco-stake/validator-registry/commit/1d05f368c330fb88a902c9143d8db0e437786d19)

Thanks @windpowerstake - true legend!

**Comment by gh0stdotexe** [comment]
I ran it through a JSON validator + cleaned things up, merging now.

**Comment by windpowerstake** [comment]
got it, thanks!!

**Pull request merged**
