### PR TITLE
Updated and Fixed chains.json and profile.json

### PR DESCRIPTION
**Pull request by crypto4punks**

### CODE REVIEW

**Comment by tombeynon** [comment]
Please fix the validation errors

**Comment by crypto4punks** [comment]
> Please fix the validation errors

i fix the validation errors. thanks.

**Review by crypto4punks — COMMENTED** [review]
i fix the validation errors on profile.json

**Review by crypto4punks — COMMENTED** [review]
it’s ready to be check. thank you

**Pull request merged**
