### PR TITLE
Beehive - Rizon - update names and min reward

### PR DESCRIPTION
**Pull request by achuchavo**

### CODE REVIEW

**Comment by tombeynon** [comment]
GitHub is having problems running actions right now so we can't validate your submission right now, but as soon as that's sorted I'll get this merged.

https://www.githubstatus.com/

**Comment by achuchavo** [comment]
> GitHub is having problems running actions right now so we can't validate your submission right now, but as soon as that's sorted I'll get this merged.
> 
> https://www.githubstatus.com/

my original chains.json file looked like this 

`{
  "$schema": "../chains.schema.json",
  "name": "Beehive",
  "chains": [
    {
      "name": "Rizon",
      "address": "rizonvaloper1gyrrvup6x3g732uhxq9x0qd4lyjjcs62j0kdhf",
      "restake": {
        "address": "rizon1sm90g8lvqu9z72pgw62t870uewu53fywtyyr99",
        "run_time":[
      "09:00",
      "21:00"
    ],
        "minimum_reward": 100000000
      }
    }
  ]
}`

however when i run `npm run autostake rizon` i still get `Not an Operator` message
Is this a problem with my json file?

**Comment by tombeynon** [comment]
No you'll see that error until this PR has been merged (or 15 minutes after that, cosmos.directory has to pull the update). Once you're registered as an operator it should all behave as expected.

**Comment by achuchavo** [comment]
> No you'll see that error until this PR has been merged (or 15 minutes after that, cosmos.directory has to pull the update). Once you're registered as an operator it should all behave as expected.

my first PR was a few hours ago and it seemed to have been merged yet i still got the message when i ran autostake. 

But like you said i will wait sometime after this PR is merged and see if everything works.

**Pull request merged**
