### PR TITLE
Add coinbase cloud restake chains for osmosis and cosmos

### PR DESCRIPTION
**Pull request by nathanhopp**

### CODE REVIEW

**Comment by tombeynon** [comment]
@nathanhopp is this meant to be a draft or is it good to merge?

**Comment by nathanhopp** [comment]
> @nathanhopp is this meant to be a draft or is it good to merge?

I was going to wait until our wallets are funded, and Axelar to be added as well.

**Comment by nathanhopp** [comment]
Hot wallets should be funded shortly. I will just open a separate PR for Axelar

**Comment by tombeynon** [comment]
Great I'll merge now. I was just checking because I've opened a few drafts accidentally 😂

**Pull request merged**
