### PR TITLE
chore: EZStaking now support IDEP

### PR DESCRIPTION
**Pull request by keupsonite**

### CODE REVIEW

**Review by tombeynon — CHANGES_REQUESTED** [review]
Hey this PR changes a lot of files. Can you check 'files changed' and resubmit if needed

**Comment by keupsonite** [comment]
Uh only my file in my folder is modified

**Comment by tombeynon** [comment]
Strange, that's not what I'm seeing. Modifies most files. I can't merge this as-is, can you create a fresh PR from current master? I think it's the force pushes causes an issue.

**Comment by keupsonite** [comment]
Capture d’écran 2022-06-26 à 13 44 12

**Comment by gh0stdotexe** [comment]
> Capture d’écran 2022-06-26 à 13 44 12

I'm seeing the same as this on my end as well - no other files are changed.

**Comment by tombeynon** [comment]
I'm seeing this so can't risk merging while I'm away from a computer. I'll be back in a few hours and will sort then. image

**Review by tombeynon — APPROVED** [review]

**Pull request merged**
