### PR TITLE
adding new validaor

### PR DESCRIPTION
**Pull request by DAStaking**
adding new validator

### CODE REVIEW

**Review by DAStaking — COMMENTED** [review]
adding new validator to the registry

**Comment by tombeynon** [comment]
No changes?

**Comment by DAStaking** [comment]
Been having issued with Git desktop; when submitting changes it is not passing the auto-validation steps.

There are changes. Adding DigitalAlchemy as a validator; with required folder and sub-files. I'll try again.

Thanks

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by DAStaking** [comment]
Been having issued with Git desktop; when submitting changes it is not passing the auto-validation steps.

There are changes. Adding DigitalAlchemy as a validator; with required folder and sub-files. I'll try again.

Thanks

Sent with[Proton Mail](https://proton.me/)secure email.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by DAStaking** [comment]
What I see when I try to merge:

[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

**Pull request closed without merging**
